### ISSUE TITLE
Error in CheckDelta

### ISSUE THREAD

**Issue by bhezy** [MyCaffe/NCCL#8]
I had to comment out CheckDelta in the test files to make them work ... what are the implications of this? I am extremely new to C++ and building via Visual Studio (like, a few days of experience), so I do not have strong debugging skills! But please let me know your thoughts. Additionally, when I use task manager to track GPU activity, I only see my original GPU doing everything in terms of processing. The new, 2nd GPU is showing copying activity, and VRAM utilization increases, so I know something is working. I wonder if it is not doing any processing because of the commented-out code! I highly appreciate any help, I bought a 2nd 3090, a beefy PSU, an NVLink, and redid all my wiring for my Windows system without knowing that cross GPU communication is not straightforward on Windows! Your repo gives me hope though.

If there is anything I can provide, please let me know. There really isn't much of an error code, it just says:

(base) [User]\GitHub\NCCL\windows\test\single\x64\Debug>all_reduce_test 300000000
 Using devices
   Rank  0 uses device  0 [0x24] NVIDIA GeForce RTX 3090
   Rank  1 uses device  1 [0x2d] NVIDIA GeForce RTX 3090

                                                 out-of-place                    in-place
      bytes             N    type      op     time  algbw  busbw      res     time  algbw  busbw      res
     300000000     300000000    char     sumCuda failure [User]\GitHub\NCCL\test\include\test_utilities.h:313 'invalid argument'

Which I traced back to the CheckDelta calls in the test codes.

**Comment by ZoroDerVonCodier** [comment]
Hi @bhezy,

What version of CUDA are you using?  I'll look into this and get back to you soon.

**Comment by bhezy** [comment]
> Hi @bhezy,
> 
> 
> 
> What version of CUDA are you using?  I'll look into this and get back to you soon.
> 
> 

Hi,
I'm using CUDA 11.7. I appreciate it!

**Comment by ZoroDerVonCodier** [comment]
Also, @bhezy ,

What version of Visual Studio Pro are you using?

**Comment by ZoroDerVonCodier** [comment]
@bhezy ,

I just checked in all samples added to the project and upgraded to Visual Studio 2022 with CUDA 11.7.  Still testing, but give that a try.  You should not need to comment out CheckDelta.

**Comment by ZoroDerVonCodier** [comment]
@bhezy,
Just made a fix to the linker lib path, you should now be set to build all samples using the nccl.sln which now has the sample projects included in it.

**Comment by bhezy** [comment]
> Also, @bhezy ,
> 
> 
> 
> What version of Visual Studio Pro are you using?

I'm using 2022. I re-cloned the repo, built the nccl.sln, and I'm still encountering the same issue in test_utilities. It's really strange, I'm not sure why! What happens when you run any of the test exe's? Does it work?

**Comment by bhezy** [comment]
> @bhezy ,
> 
> 
> 
> I just checked in all samples added to the project and upgraded to Visual Studio 2022 with CUDA 11.7.  Still testing, but give that a try.  You should not need to comment out CheckDelta.

So, I had a small, very partial fix. I still had to comment out CheckDelta to get it to work, which I'd like to figure out why I had to do that in the first place, but I was able to visualize GPU effort in task manager after plugging in my HDMIs to both GPUs. I can see that using your nccl program, I can make both GPUs work properly. This shows just how new I am to dual GPU programming! Could be something specific to these gaming style GPUs, since workstation GPUs won't necessarily have display slots.

That does still leave the question on how to make CheckDelta work!

**Comment by ZoroDerVonCodier** [comment]
@bhezy ,

Correct - I just fixed the bug causing CheckDelta to crash - the fix is now checked in.

**Comment by ZoroDerVonCodier** [comment]
@bhezy,

One thing to keep in mind is that NCCL works best when run in TCC mode - see https://docs.nvidia.com/gameworks/content/developertools/desktop/tesla_compute_cluster.htm  

The gaming GPU's such as 3090 do no support TCC mode.  You can check this by running nvidia_smi.exe - see https://developer.nvidia.com/nvidia-system-management-interface

nvidia_smi.exe is used to enable TCC mode which only works on Titan X, Titan Xp and other higher end GPUs like the RTX A6000.  TCC mode nearly doubles the speed but cannot be used when a monitor is connected.

**Comment by bhezy** [comment]
Thank you @ZoroDerVonCodier! That did the trick. I'll close the issue, but regarding your last comment ..... well that makes a lot of sense. I compared my performance to something online:

https://github.com/tbennun/nccl-windows/tree/8.0
![image](https://github.com/MyCaffe/NCCL/assets/64805252/b4fa4fd8-15f1-4403-b12e-9c11b2144d52)

While the same test on my system has the following performance:

![image](https://github.com/MyCaffe/NCCL/assets/64805252/4b065b60-add7-468d-b208-2d35d0949b43)

I am seeing my tests time between 13-21 on my dual RTX 3090 system while their 4 GTX Titan X system (7 years ago) had test times of ~1.6 (I believe both are in milliseconds). So, a partial reason for this is that they used a system with TCC enabled?

**Comment by ZoroDerVonCodier** [comment]
@bhezy ,

Yes most likely because they have TCC enabled - it has a really big impact on performance.

**Comment by bhezy** [comment]
@ZoroDerVonCodier thank you, that makes a ton of sense. I highly appreciate your help on this issue!
